export enum ApiErrorCode {
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  FORBIDDEN = 'FORBIDDEN',
  UNAUTHORIZED = 'UNAUTHORIZED',
  RATE_LIMITED = 'RATE_LIMITED',
  CONFLICT = 'CONFLICT',

  ORDER_NOT_FOUND = 'ORDER_NOT_FOUND',
  ORDER_ALREADY_REVERSED = 'ORDER_ALREADY_REVERSED',
  ORDER_VOID_SAME_DAY_ONLY = 'ORDER_VOID_SAME_DAY_ONLY',
  ORDER_REFUND_NOT_COMPLETED = 'ORDER_REFUND_NOT_COMPLETED',
  ORDER_REFUND_SAME_DAY = 'ORDER_REFUND_SAME_DAY',
  ORDER_REFUND_NOT_ALLOWED = 'ORDER_REFUND_NOT_ALLOWED',
  ORDER_STATUS_INVALID = 'ORDER_STATUS_INVALID',

  PRODUCT_NOT_FOUND = 'PRODUCT_NOT_FOUND',
  PRODUCT_RECIPE_REQUIRED = 'PRODUCT_RECIPE_REQUIRED',
  INVALID_MODIFIER_SELECTION = 'INVALID_MODIFIER_SELECTION',
  CUSTOMER_NOT_FOUND = 'CUSTOMER_NOT_FOUND',
  CUSTOMER_PHONE_REQUIRED = 'CUSTOMER_PHONE_REQUIRED',
  INSUFFICIENT_LOYALTY_POINTS = 'INSUFFICIENT_LOYALTY_POINTS',
  PROMOTION_INVALID = 'PROMOTION_INVALID',
  PROMOTION_NOT_STARTED = 'PROMOTION_NOT_STARTED',
  PROMOTION_EXPIRED = 'PROMOTION_EXPIRED',
  PROMOTION_MIN_PURCHASE = 'PROMOTION_MIN_PURCHASE',

  BRANCH_ACCESS_DENIED = 'BRANCH_ACCESS_DENIED',
  BRANCH_NOT_ASSIGNED = 'BRANCH_NOT_ASSIGNED',

  SETTLEMENT_NOT_FOUND = 'SETTLEMENT_NOT_FOUND',
  SETTLEMENT_ALREADY_APPROVED = 'SETTLEMENT_ALREADY_APPROVED',
}
