import { Test, TestingModule } from '@nestjs/testing';
import { ProcurementService } from './procurement.service';
import { PrismaService } from '../prisma/prisma.service';
import { AuditService } from '../audit/audit.service';
import { OutboxService } from '../outbox/outbox.service';
import { BadRequestException } from '@nestjs/common';
import {
  MockPrismaService,
  PrismaServiceMockProvider,
} from '../prisma/prisma.service.mock';

describe('ProcurementService', () => {
  let service: ProcurementService;
  let prisma: MockPrismaService;

  beforeEach(async () => {
    const module: TestingModule = await Test.createTestingModule({
      providers: [
        ProcurementService,
        PrismaServiceMockProvider,
        { provide: AuditService, useValue: { logAction: jest.fn() } },
        { provide: OutboxService, useValue: { enqueue: jest.fn() } },
      ],
    }).compile();

    service = module.get(ProcurementService);
    prisma = module.get(PrismaService);
  });

  describe('submitPO', () => {
    it('moves DRAFT PO with items to PENDING', async () => {
      prisma.purchaseOrder.findUnique.mockResolvedValue({
        id: 1,
        branchId: 2,
        poNumber: 'PO-AUTO-1',
        status: 'DRAFT',
        isAutoGenerated: true,
        items: [{ id: 1, ingredientId: 3, quantityRequested: 100, unitPrice: 1 }],
      } as any);
      prisma.purchaseOrder.update.mockResolvedValue({
        id: 1,
        status: 'PENDING',
      } as any);

      const result = await service.submitPO(1, 9, {
        userId: 9,
        role: 'MANAGER',
        branchId: 2,
      });

      expect(result.status).toBe('PENDING');
      expect(prisma.purchaseOrder.update).toHaveBeenCalledWith({
        where: { id: 1 },
        data: { status: 'PENDING' },
      });
    });

    it('rejects empty DRAFT PO', async () => {
      prisma.purchaseOrder.findUnique.mockResolvedValue({
        id: 1,
        branchId: 2,
        status: 'DRAFT',
        items: [],
      } as any);

      await expect(
        service.submitPO(1, 9, { userId: 9, role: 'MANAGER', branchId: 2 }),
      ).rejects.toThrow(BadRequestException);
    });
  });
});
