import { Injectable } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';

export const AUDIT_ACTIONS = {
  VOID_ORDER: 'VOID_ORDER',
  REFUND_ORDER: 'REFUND_ORDER',
  GENERATE_PAYROLL: 'GENERATE_PAYROLL',
  APPROVE_PAYROLL: 'APPROVE_PAYROLL',
  CREATE_PO: 'CREATE_PO',
  SUBMIT_PO: 'SUBMIT_PO',
  APPROVE_PO: 'APPROVE_PO',
  REJECT_PO: 'REJECT_PO',
  RECEIVE_PO: 'RECEIVE_PO',
  PAY_PO: 'PAY_PO',
  UPDATE_SETTINGS: 'UPDATE_SETTINGS',
  CREATE_STOCK_COUNT: 'CREATE_STOCK_COUNT',
  APPROVE_STOCK_COUNT: 'APPROVE_STOCK_COUNT',
  MANUAL_ADJUSTMENT: 'MANUAL_ADJUSTMENT',
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];

export const AUDIT_TARGETS = {
  ORDER: 'Order',
  PAYROLL_RUN: 'PayrollRun',
  PURCHASE_ORDER: 'PurchaseOrder',
  SYSTEM_SETTING: 'SystemSetting',
  STOCK_COUNT: 'StockCount',
  STOCK_ADJUSTMENT: 'StockAdjustment',
} as const;

type JsonLike =
  | string
  | number
  | boolean
  | null
  | { [key: string]: JsonLike }
  | JsonLike[];

export type AuditTargetByAction = {
  [AUDIT_ACTIONS.VOID_ORDER]: typeof AUDIT_TARGETS.ORDER;
  [AUDIT_ACTIONS.REFUND_ORDER]: typeof AUDIT_TARGETS.ORDER;
  [AUDIT_ACTIONS.GENERATE_PAYROLL]: typeof AUDIT_TARGETS.PAYROLL_RUN;
  [AUDIT_ACTIONS.APPROVE_PAYROLL]: typeof AUDIT_TARGETS.PAYROLL_RUN;
  [AUDIT_ACTIONS.CREATE_PO]: typeof AUDIT_TARGETS.PURCHASE_ORDER;
  [AUDIT_ACTIONS.SUBMIT_PO]: typeof AUDIT_TARGETS.PURCHASE_ORDER;
  [AUDIT_ACTIONS.APPROVE_PO]: typeof AUDIT_TARGETS.PURCHASE_ORDER;
  [AUDIT_ACTIONS.REJECT_PO]: typeof AUDIT_TARGETS.PURCHASE_ORDER;
  [AUDIT_ACTIONS.RECEIVE_PO]: typeof AUDIT_TARGETS.PURCHASE_ORDER;
  [AUDIT_ACTIONS.PAY_PO]: typeof AUDIT_TARGETS.PURCHASE_ORDER;
  [AUDIT_ACTIONS.UPDATE_SETTINGS]: typeof AUDIT_TARGETS.SYSTEM_SETTING;
  [AUDIT_ACTIONS.CREATE_STOCK_COUNT]: typeof AUDIT_TARGETS.STOCK_COUNT;
  [AUDIT_ACTIONS.APPROVE_STOCK_COUNT]: typeof AUDIT_TARGETS.STOCK_COUNT;
  [AUDIT_ACTIONS.MANUAL_ADJUSTMENT]: typeof AUDIT_TARGETS.STOCK_ADJUSTMENT;
};

export type AuditDetailsByAction = {
  [AUDIT_ACTIONS.VOID_ORDER]: {
    branchId: number;
    netAmount: number;
    totalCogs: number;
  };
  [AUDIT_ACTIONS.REFUND_ORDER]: {
    branchId: number;
    netAmount: number;
    totalCogs: number;
    reason?: string;
  };
  [AUDIT_ACTIONS.GENERATE_PAYROLL]: {
    branchId: number;
    month: number;
    year: number;
    payslipCount: number;
  };
  [AUDIT_ACTIONS.APPROVE_PAYROLL]: {
    branchId: number | null;
    month: number;
    year: number;
  };
  [AUDIT_ACTIONS.CREATE_PO]: {
    poNumber: string;
  };
  [AUDIT_ACTIONS.SUBMIT_PO]: {
    poNumber: string;
    isAutoGenerated: boolean;
  };
  [AUDIT_ACTIONS.APPROVE_PO]: {
    poNumber: string;
  };
  [AUDIT_ACTIONS.REJECT_PO]: {
    poNumber: string;
  };
  [AUDIT_ACTIONS.RECEIVE_PO]: {
    poNumber: string;
  };
  [AUDIT_ACTIONS.PAY_PO]: {
    poNumber: string;
    amount: number;
    method: string;
  };
  [AUDIT_ACTIONS.UPDATE_SETTINGS]: {
    keys: string[];
  };
  [AUDIT_ACTIONS.CREATE_STOCK_COUNT]: {
    branchId: number;
    isBlind: boolean;
    lineCount: number;
  };
  [AUDIT_ACTIONS.APPROVE_STOCK_COUNT]: {
    branchId: number;
    adjustedLines: number;
    netVarianceValue: number;
  };
  [AUDIT_ACTIONS.MANUAL_ADJUSTMENT]: {
    branchId: number;
    ingredientId: number;
    quantityDelta: number;
    reason: string;
  };
};

@Injectable()
export class AuditService {
  constructor(private prisma: PrismaService) {}

  async logAction<TAction extends AuditAction>(
    userId: number,
    action: TAction,
    targetType: AuditTargetByAction[TAction],
    targetId?: number,
    details?: AuditDetailsByAction[TAction] | JsonLike,
  ) {
    const detailsString =
      details == null
        ? undefined
        : typeof details === 'object'
          ? JSON.stringify(details)
          : String(details);

    return this.prisma.auditLog.create({
      data: {
        userId,
        action,
        targetType,
        targetId,
        details: detailsString,
      },
    });
  }

  async getLogs(limit = 100, offset = 0, branchId?: number) {
    return this.prisma.auditLog.findMany({
      take: limit,
      skip: offset,
      where: branchId ? { user: { branchId } } : undefined,
      orderBy: { createdAt: 'desc' },
      include: {
        user: {
          select: { id: true, name: true, email: true, role: true },
        },
      },
    });
  }
}
