export const HR_ENDPOINTS = {
  clockIn: '/hr/clock-in',
  clockOut: '/hr/clock-out',
  attendanceMe: '/hr/attendance/me',
  attendanceStatus: '/hr/attendance/status',
  shiftsByBranch: (branchId: number) => `/hr/shifts/branch/${branchId}`,
  shiftsMe: '/hr/shifts/me',
  createShift: '/hr/shifts',
  leave: (branchId?: number) => `/hr/leave${branchId ? `?branchId=${branchId}` : ''}`,
  leaveMe: '/hr/leave/me',
  createLeave: '/hr/leave',
  updateLeaveStatus: (id: number) => `/hr/leave/${id}/status`,
  payrollRuns: (branchId: number) => `/hr/payroll-runs?branchId=${branchId}`,
  generatePayroll: '/hr/payroll/generate',
  approvePayrollRun: (id: number) => `/hr/payroll-runs/${id}/approve`,
  users: (branchId?: number) => `/hr/users${branchId ? `?branchId=${branchId}` : ''}`,
  updateHourlyRate: (userId: number) => `/hr/users/${userId}/rate`,
  createUser: '/hr/users',
  updateUser: (id: number) => `/hr/users/${id}`,
} as const;
