version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    ignore:
      - dependency-name: eslint
        update-types: [version-update:semver-major]
      - dependency-name: "@eslint/js"
        update-types: [version-update:semver-major]
    groups:
      nestjs:
        patterns:
          - "@nestjs/*"
          - nestjs
      next:
        patterns:
          - next
          - eslint-config-next
          - "@next/*"
      prisma:
        patterns:
          - prisma
          - "@prisma/*"
      playwright:
        patterns:
          - "@playwright/*"
          - playwright
      react:
        patterns:
          - react
          - react-dom
          - "@types/react"
          - "@types/react-dom"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
