// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Supabase: use direct connection (5432) for migrations; pooler (6543) hangs on DDL.
    url: process.env["DIRECT_URL"] ?? env("DATABASE_URL"),
  },
});
