export function logSeedSummary(): void {
  console.log('Seeding completed!');
  console.log('');
  console.log('Demo logins (password: password123):');
  console.log('  admin@branchbrew.dev          — Super Admin');
  console.log('  manager@branchbrew.dev        — Downtown Manager');
  console.log('  staff.siam@branchbrew.dev     — Downtown Cashier');
  console.log('  manager.asok@branchbrew.dev   — Riverside Manager');
  console.log('  staff.asok@branchbrew.dev     — Riverside Barista');
  console.log('');
  console.log('Promo codes: WELCOME10 | BAHT20OFF (active) | SUMMER24 (inactive)');
  console.log('Member phones: 0811111111 … 0877777777 (8 customers, mixed tiers)');
  console.log('');
  console.log('');
  console.log('Dashboard (/) — after seed:');
  console.log('  Today\'s sales widget — ~$4k+ Downtown / ~$1.5k+ Riverside with positive vs-yesterday growth');
  console.log('  Revenue chart — 7-day trend with daily completed orders');
  console.log('  Top products — Iced Latte, Americano, bakery items from today\'s volume');
  console.log('  Inventory alerts — low stock cups @ Riverside + expiring batches');
  console.log('');
  console.log('POS / KDS:');
  console.log('  /pos/terminal — 24 active menu items (Coffee, Bakery, Tea, Beverage)');
  console.log('  Downtown KDS — 5+ tickets (new + cooking, incl. overdue demo)');
  console.log('  Riverside KDS — 1 pending ticket | /pos/orders — refunds & promos');
  console.log('');
  console.log('Inventory:');
  console.log('  /inventory — low stock cups @ Riverside | batches expiring in 3 days');
  console.log('  /inventory/transfers — pending, shipped, completed, cancelled');
  console.log('  /inventory/batches — expired oat milk @ Downtown (auto-waste cron)');
  console.log('');
  console.log('Procurement: /procurement — DRAFT, PENDING, APPROVED, RECEIVED POs');
  console.log('Kitchen: select Central Kitchen → /kitchen — planned, in-progress, completed');
  console.log('');
  console.log('Finance:');
  console.log('  /finance/overview — settlements (pending @ Downtown & Riverside)');
  console.log('  /finance/ledger — 5 journal entries | expenses across both branches');
  console.log('');
  console.log('HR / Payroll:');
  console.log('  /hr — shifts, attendance, leave (pending/approved/rejected)');
  console.log('  /hr/payroll — approved run (last month) + draft @ Riverside');
  console.log('');
  console.log('Assets: /assets/equipment — Downtown, Riverside, Central Kitchen');
  console.log('CRM: /crm/customers — 8 members | Settings audit log — 20+ entries');
}
