import { ApiProperty } from '@nestjs/swagger';
import { POStatus } from '@prisma/client';
import { BranchResponseDto } from '../../branches/dto/branch-response.dto';
import { IngredientSummaryDto } from '../../inventory/dto/inventory-response.dto';

export class SupplierResponseDto {
  @ApiProperty({ example: 1 })
  id: number;

  @ApiProperty({ example: 'Fresh Farms Co.' })
  name: string;

  @ApiProperty({
    type: String,
    example: 'orders@freshfarms.dev',
    nullable: true,
  })
  contactEmail: string | null;

  @ApiProperty({ type: String, example: '+66 2 123 4567', nullable: true })
  phone: string | null;

  @ApiProperty({ type: String, format: 'date-time' })
  createdAt: Date;

  @ApiProperty({ type: String, format: 'date-time' })
  updatedAt: Date;
}

export class PurchaseOrderItemResponseDto {
  @ApiProperty({ example: 1 })
  id: number;

  @ApiProperty({ example: 10 })
  poId: number;

  @ApiProperty({ example: 3 })
  ingredientId: number;

  @ApiProperty({ example: 24 })
  quantityRequested: number;

  @ApiProperty({ example: 45.5 })
  unitPrice: number;

  @ApiProperty({ type: IngredientSummaryDto, required: false })
  ingredient?: IngredientSummaryDto;
}

export class PurchaseOrderResponseDto {
  @ApiProperty({ example: 1 })
  id: number;

  @ApiProperty({ example: 'PO-2026-0001' })
  poNumber: string;

  @ApiProperty({ example: 1 })
  branchId: number;

  @ApiProperty({ example: 2 })
  supplierId: number;

  @ApiProperty({ enum: POStatus, example: POStatus.DRAFT })
  status: POStatus;

  @ApiProperty({ example: false })
  isAutoGenerated: boolean;

  @ApiProperty({ type: String, format: 'date-time' })
  createdAt: Date;

  @ApiProperty({ type: String, format: 'date-time' })
  updatedAt: Date;

  @ApiProperty({ type: SupplierResponseDto, required: false })
  supplier?: SupplierResponseDto;

  @ApiProperty({ type: BranchResponseDto, required: false })
  branch?: BranchResponseDto;

  @ApiProperty({
    type: PurchaseOrderItemResponseDto,
    isArray: true,
    required: false,
  })
  items?: PurchaseOrderItemResponseDto[];
}
