import type { PurchaseOrder } from "@/types/api";
import { toNumber } from "@/lib/money";

export type POStatusFilter = "ALL" | "DRAFT" | "PENDING" | "APPROVED" | "RECEIVED";
export type POHighlightFilter = "ALL" | "auto-draft";

export function poIsAutoDraft(order: PurchaseOrder): boolean {
  return order.status === "DRAFT" && order.isAutoGenerated === true;
}

export function computePurchaseOrderTotal(order: PurchaseOrder): number {
  return (order.items ?? []).reduce(
    (sum, item) => sum + toNumber(item.quantityRequested) * toNumber(item.unitPrice),
    0,
  );
}

export function matchesPOStatusFilter(order: PurchaseOrder, filter: POStatusFilter): boolean {
  if (filter === "ALL") return true;
  return order.status === filter;
}

export function matchesPOHighlightFilter(
  order: PurchaseOrder,
  filter: POHighlightFilter,
): boolean {
  if (filter === "ALL") return true;
  return poIsAutoDraft(order);
}

export function matchesPOSupplierFilter(
  order: PurchaseOrder,
  supplierId: number | null,
): boolean {
  if (supplierId == null) return true;
  return order.supplierId === supplierId;
}

export function summarizePurchaseOrders(orders: PurchaseOrder[]) {
  let draft = 0;
  let pending = 0;
  let approved = 0;
  let received = 0;
  let autoDraft = 0;

  for (const order of orders) {
    switch (order.status) {
      case "DRAFT":
        draft += 1;
        if (poIsAutoDraft(order)) autoDraft += 1;
        break;
      case "PENDING":
        pending += 1;
        break;
      case "APPROVED":
        approved += 1;
        break;
      case "RECEIVED":
        received += 1;
        break;
    }
  }

  return { total: orders.length, draft, pending, approved, received, autoDraft };
}
