// AUTO-GENERATED by scripts/generate-enums.mjs — do not edit manually.
// Source: backend/prisma/schema.prisma

export type Role = 'SUPER_ADMIN' | 'MANAGER' | 'STAFF';

export type EmploymentType = 'FULL_TIME' | 'PART_TIME';

export type BatchStatus = 'ACTIVE' | 'DEPLETED' | 'EXPIRED';

export type TransferStatus = 'PENDING' | 'SHIPPED' | 'COMPLETED' | 'CANCELLED';

export type StockCountStatus = 'DRAFT' | 'SUBMITTED' | 'APPROVED' | 'CANCELLED';

export type StockAdjustmentReason = 'COUNT_VARIANCE' | 'DAMAGE' | 'CORRECTION';

export type NotificationType = 'LOW_STOCK' | 'BATCH_EXPIRING' | 'MAINTENANCE_DUE' | 'LEAVE_DECIDED' | 'PO_PENDING_APPROVAL' | 'STOCK_COUNT_PENDING';

export type Tier = 'REGULAR' | 'SILVER' | 'GOLD' | 'PLATINUM';

export type PaymentMethod = 'CASH' | 'CREDIT_CARD' | 'QR_PROMPTPAY';

export type DiscountType = 'PERCENTAGE' | 'FIXED_AMOUNT';

export type OrderStatus = 'PENDING' | 'PREPARING' | 'COMPLETED' | 'CANCELLED' | 'REFUNDED';

export type POStatus = 'DRAFT' | 'PENDING' | 'APPROVED' | 'RECEIVED';

export type POPaymentStatus = 'UNPAID' | 'PAID';

export type SupplierPaymentMethod = 'CASH' | 'BANK_TRANSFER';

export type ShiftStatus = 'SCHEDULED' | 'COMPLETED' | 'ABSENT' | 'CANCELLED';

export type LeaveType = 'SICK' | 'ANNUAL' | 'UNPAID';

export type LeaveStatus = 'PENDING' | 'APPROVED' | 'REJECTED';

export type SettlementStatus = 'PENDING' | 'APPROVED' | 'REJECTED';

export type PayrollStatus = 'DRAFT' | 'APPROVED' | 'PAID';

export type EquipmentType = 'ESPRESSO_MACHINE' | 'GRINDER' | 'BLENDER' | 'POS_SYSTEM' | 'REFRIGERATOR' | 'OTHER';

export type EquipmentStatus = 'ACTIVE' | 'MAINTENANCE' | 'BROKEN' | 'RETIRED';

export type AccountType = 'ASSET' | 'LIABILITY' | 'EQUITY' | 'REVENUE' | 'EXPENSE';

export type JournalStatus = 'DRAFT' | 'POSTED' | 'VOIDED';

export type ProductionStatus = 'DRAFT' | 'PLANNED' | 'IN_PROGRESS' | 'COMPLETED' | 'CANCELLED';

export type OutboxStatus = 'PENDING' | 'PROCESSING' | 'COMPLETED' | 'FAILED';
