"use client";

import { useEffect, useState } from "react";
import { getPurchaseOrders, fetchAPI, approvePurchaseOrder, rejectPurchaseOrder, receivePurchaseOrder } from "@/lib/api";
import { useAuth } from "@/context/AuthContext";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Plus, CheckCircle2, XCircle, CheckSquare } from "lucide-react";
import { toast } from "sonner";

export default function ProcurementPage() {
  const { user, activeBranchId } = useAuth();
  const [pos, setPos] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    loadPOs();
  }, [activeBranchId, user]);

  const loadPOs = async () => {
    try {
      const data = await getPurchaseOrders();
      // Filter by active branch unless Super Admin wants to see all
      if (user?.role === 'SUPER_ADMIN' && !activeBranchId) {
        setPos(data);
      } else if (activeBranchId) {
        setPos(data.filter((po: any) => po.branchId === activeBranchId));
      } else {
        setPos(data);
      }
    } catch (error) {
      console.error(error);
    } finally {
      setLoading(false);
    }
  };

  const handleApprove = async (poId: number) => {
    try {
      await approvePurchaseOrder(poId);
      toast.success("Purchase Order approved successfully!");
      loadPOs();
    } catch (error: any) {
      toast.error(error.message || "Failed to approve PO");
    }
  };

  const handleReject = async (poId: number) => {
    try {
      await rejectPurchaseOrder(poId);
      toast.success("Purchase Order rejected.");
      loadPOs();
    } catch (error: any) {
      toast.error(error.message || "Failed to reject PO");
    }
  };

  const handleReceive = async (poId: number) => {
    try {
      await receivePurchaseOrder(poId);
      toast.success("Purchase Order received! Inventory updated.");
      loadPOs();
    } catch (error: any) {
      toast.error(error.message || "Failed to receive PO");
    }
  };

  const getStatusBadge = (status: string) => {
    switch (status) {
      case "APPROVED": return "bg-blue-100 text-blue-800 dark:bg-blue-900/30 dark:text-blue-300";
      case "RECEIVED": return "bg-emerald-100 text-emerald-800 dark:bg-emerald-900/30 dark:text-emerald-300";
      case "PENDING": return "bg-amber-100 text-amber-800 dark:bg-amber-900/30 dark:text-amber-300";
      case "DRAFT": return "bg-slate-100 text-slate-800 dark:bg-slate-800 dark:text-slate-300";
      default: return "bg-slate-100 text-slate-800";
    }
  };

  if (loading) return <div>Loading...</div>;

  const canApprove = user?.role === "SUPER_ADMIN" || user?.role === "MANAGER";

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <div className="ml-auto">
          <Button className="bg-blue-600 hover:bg-blue-700">
            <Plus className="w-4 h-4 mr-2" />
            Create PO
          </Button>
        </div>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Purchase Orders</CardTitle>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>PO Number</TableHead>
                <TableHead>Branch</TableHead>
                <TableHead>Supplier</TableHead>
                <TableHead>Status</TableHead>
                <TableHead className="text-right">Action</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {pos.map((po) => (
                <TableRow key={po.id}>
                  <TableCell className="font-medium">
                    <div className="flex items-center gap-2">
                      {po.poNumber}
                      {po.isAutoGenerated && <Badge variant="outline" className="bg-blue-50 dark:bg-blue-900/30 text-blue-600 dark:text-blue-400 border-blue-200 dark:border-blue-800 text-[10px] px-1 py-0 uppercase">Auto</Badge>}
                    </div>
                  </TableCell>
                  <TableCell>{po.branch.name}</TableCell>
                  <TableCell>{po.supplier.name}</TableCell>
                  <TableCell>
                    <Badge variant="secondary" className={getStatusBadge(po.status)}>
                      {po.status}
                    </Badge>
                  </TableCell>
                  <TableCell className="text-right">
                    <div className="flex justify-end gap-2">
                      {po.status === 'PENDING' && canApprove && (
                        <>
                          <Button size="sm" variant="outline" className="text-blue-600 border-blue-200 hover:bg-blue-50 dark:border-blue-800/50 dark:hover:bg-blue-900/30" onClick={() => handleApprove(po.id)}>
                            <CheckSquare className="w-4 h-4 mr-1.5" />
                            Approve
                          </Button>
                          <Button size="sm" variant="outline" className="text-rose-600 border-rose-200 hover:bg-rose-50 dark:border-rose-800/50 dark:hover:bg-rose-900/30" onClick={() => handleReject(po.id)}>
                            <XCircle className="w-4 h-4 mr-1.5" />
                            Reject
                          </Button>
                        </>
                      )}
                      
                      {po.status === 'APPROVED' && (
                        <Button size="sm" variant="outline" className="text-emerald-600 border-emerald-200 hover:bg-emerald-50 dark:border-emerald-800/50 dark:hover:bg-emerald-900/30" onClick={() => handleReceive(po.id)}>
                          <CheckCircle2 className="w-4 h-4 mr-1.5" />
                          Receive Goods
                        </Button>
                      )}
                    </div>
                  </TableCell>
                </TableRow>
              ))}
              {pos.length === 0 && (
                <TableRow>
                  <TableCell colSpan={5} className="text-center text-slate-500 dark:text-slate-400 py-8">
                    No purchase orders found.
                  </TableCell>
                </TableRow>
              )}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  );
}
