#!/usr/bin/env node
/**
 * Generates packages/types/src/enums.ts from backend/prisma/schema.prisma.
 * Run: node scripts/generate-enums.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, '..');
const schemaPath = path.join(rootDir, 'backend/prisma/schema.prisma');
const outputPath = path.join(rootDir, 'packages/types/src/enums.ts');

const schema = readFileSync(schemaPath, 'utf8');

/** @type {Map<string, string[]>} */
const enums = new Map();

const enumBlockRegex = /enum\s+(\w+)\s*\{([^}]*)\}/g;
let match;

while ((match = enumBlockRegex.exec(schema)) !== null) {
  const name = match[1];
  const values = match[2]
    .split('\n')
    .map((line) => line.replace(/\/\/.*$/, '').trim())
    .filter((line) => line.length > 0 && !line.startsWith('@@'));
  enums.set(name, values);
}

const lines = [
  '// AUTO-GENERATED by scripts/generate-enums.mjs — do not edit manually.',
  '// Source: backend/prisma/schema.prisma',
  '',
];

for (const [name, values] of enums) {
  const union = values.map((v) => `'${v}'`).join(' | ');
  lines.push(`export type ${name} = ${union};`);
  lines.push('');
}

writeFileSync(outputPath, lines.join('\n'));
console.log(`Generated ${enums.size} enums → ${path.relative(rootDir, outputPath)}`);
