import { describe, expect, it } from "vitest";
import type { PurchaseOrder } from "@/types/api";
import {
  computePurchaseOrderTotal,
  matchesPOHighlightFilter,
  matchesPOStatusFilter,
  poIsAutoDraft,
  summarizePurchaseOrders,
} from "./purchase-order-filters";

function po(overrides: Partial<PurchaseOrder> = {}): PurchaseOrder {
  return {
    id: 1,
    poNumber: "PO-001",
    branchId: 1,
    supplierId: 2,
    status: "PENDING",
    createdAt: "2026-01-01T00:00:00Z",
    items: [{ id: 1, poId: 1, ingredientId: 3, quantityRequested: 2, unitPrice: 10 }],
    ...overrides,
  };
}

describe("purchase-order-filters", () => {
  it("detects auto drafts and totals", () => {
    expect(poIsAutoDraft(po({ status: "DRAFT", isAutoGenerated: true }))).toBe(true);
    expect(computePurchaseOrderTotal(po())).toBe(20);
  });

  it("filters by status and highlight", () => {
    expect(matchesPOStatusFilter(po(), "PENDING")).toBe(true);
    expect(
      matchesPOHighlightFilter(po({ status: "DRAFT", isAutoGenerated: true }), "auto-draft"),
    ).toBe(true);
  });

  it("summarizes PO counts", () => {
    const summary = summarizePurchaseOrders([
      po(),
      po({ id: 2, status: "DRAFT", isAutoGenerated: true }),
    ]);
    expect(summary.pending).toBe(1);
    expect(summary.autoDraft).toBe(1);
  });
});
